import { useState } from 'react'

const translations = {
  es: {
    tagline: 'Nutrición canina personalizada con IA',
    createAccount: 'Crear cuenta',
    login: 'Iniciar sesión',
    loginTitle: 'Bienvenido de nuevo',
    email: 'Email',
    password: 'Contraseña',
    loginBtn: 'Entrar',
    loginError: 'Email o contraseña incorrectos',
    loading: 'Cargando...',
    noAccount: '¿No tienes cuenta?',
    registerLink: 'Regístrate',
    registerTitle: 'Crear cuenta',
    name: 'Nombre',
    city: 'Ciudad',
    registerBtn: 'Registrarse',
    registerError: 'Error al registrarse. Inténtalo de nuevo.',
    hasAccount: '¿Ya tienes cuenta?',
    loginLink: 'Inicia sesión',
    newPetTitle: 'Añade a tu perro',
    newPetSubtitle: 'Cuéntanos sobre tu mascota para personalizar su nutrición',
    petName: 'Nombre',
    breed: 'Raza',
    weight: 'Peso (kg)',
    ageMonths: 'Edad (meses)',
    sex: 'Sexo',
    male: 'Macho',
    female: 'Hembra',
    allergies: 'Alergias',
    allergiesPlaceholder: 'pollo, cereales... o ninguna',
    savePet: 'Guardar y continuar',
    petError: 'Error al guardar la mascota. Inténtalo de nuevo.',
    logout: 'Cerrar sesión',
    hello: 'Hola',
    homeSubtitle: 'El bienestar de tu perro, personalizado con IA',
    myPets: 'Mis mascotas',
    months: 'meses',
    allergies: 'Alergias',
    chatWithKahu: 'Chatear con Kahu',
    noPets: 'Aún no tienes mascotas registradas',
    addPet: 'Añadir mascota',
    quickActions: 'Accesos rápidos',
    chat: 'Chat',
    profile: 'Perfil',
    home: 'Inicio',
    chatWelcome: '¡Hola! Soy Kahu, tu asistente de nutrición canina.',
    chatContext: 'Estoy listo para ayudarte con',
    chatPlaceholder: 'Escribe tu pregunta...',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirmDelete: '¿Seguro que quieres eliminar esta mascota?',
    dietType: 'Tipo de dieta',
    cooked: 'Cocinada',
    mixed: 'Mixta',
    savedMenus: 'Menús guardados',
    noMenus: 'Aún no hay menús guardados',
    goToChat: 'Ir al chat',
    confirmDeletePlan: '¿Seguro que quieres eliminar este menú?',
    weight: 'Peso',
    mealsPerDay: 'Tomas al día',
    meal: 'toma',
    meals: 'tomas',
    weightEvolution: 'Evolución peso',
    vetHistory: 'Historial veterinario',
    vetVisits: 'Visitas veterinarias',
    newVisit: '+ Nueva visita',
    visitDate: 'Fecha de visita',
    nextAppointment: 'Próxima cita (opcional)',
    reason: 'Motivo',
    reasonPlaceholder: 'Revisión anual, vacunación...',
    description: 'Descripción',
    descriptionPlaceholder: 'Descripción de la visita...',
    treatment: 'Tratamiento',
    treatmentPlaceholder: 'Medicación, pautas, observaciones...',
    saveRecord: 'Guardar registro',
    noVetRecords: 'Aún no hay registros veterinarios.',
    addFirstVisit: '+ Añadir primera visita',
    nextVisit: 'Próxima cita',
    treatments: 'Tratamientos',
    newTreatment: '+ Nuevo tratamiento',
    treatmentName: 'Nombre del tratamiento',
    treatmentNamePlaceholder: 'Antiparasitario, vacuna...',
    frequency: 'Frecuencia',
    lastDose: 'Última dosis',
    notes: 'Notas (opcional)',
    notesPlaceholder: 'Observaciones...',
    saveTreatment: 'Guardar tratamiento',
    noTreatments: 'No hay tratamientos registrados.',
    adminToday: '✓ Administrado hoy',
    daysLeft: 'En {n} días',
    tomorrow: 'Mañana',
    today: 'Hoy',
    overdue: 'Atrasado {n} días',
  },

  en: {
    tagline: 'Personalized dog nutrition with AI',
    createAccount: 'Create account',
    login: 'Log in',
    loginTitle: 'Welcome back',
    email: 'Email',
    password: 'Password',
    loginBtn: 'Sign in',
    loginError: 'Invalid email or password',
    loading: 'Loading...',
    noAccount: "Don't have an account?",
    registerLink: 'Sign up',
    registerTitle: 'Create account',
    name: 'Name',
    city: 'City',
    registerBtn: 'Sign up',
    registerError: 'Registration failed. Please try again.',
    hasAccount: 'Already have an account?',
    loginLink: 'Log in',
    newPetTitle: 'Add your dog',
    newPetSubtitle: 'Tell us about your pet to personalize their nutrition',
    petName: 'Name',
    breed: 'Breed',
    weight: 'Weight (kg)',
    ageMonths: 'Age (months)',
    sex: 'Sex',
    male: 'Male',
    female: 'Female',
    allergies: 'Allergies',
    allergiesPlaceholder: 'chicken, grains... or none',
    savePet: 'Save and continue',
    petError: 'Error saving pet. Please try again.',
    logout: 'Log out',
    hello: 'Hello',
    homeSubtitle: 'Your dog\'s wellbeing, personalized with AI',
    myPets: 'My pets',
    months: 'months',
    allergies: 'Allergies',
    chatWithKahu: 'Chat with Kahu',
    noPets: 'No pets registered yet',
    addPet: 'Add pet',
    quickActions: 'Quick actions',
    chat: 'Chat',
    profile: 'Profile',
    home: 'Home',
    chatWelcome: 'Hi! I\'m Kahu, your canine nutrition assistant.',
    chatContext: 'I\'m ready to help you with',
    chatPlaceholder: 'Type your question...',
    save: 'Save',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete this pet?',
    dietType: 'Diet type',
    cooked: 'Cooked',
    mixed: 'Mixed',
    savedMenus: 'Saved menus',
    noMenus: 'No saved menus yet',
    goToChat: 'Go to chat',
    confirmDeletePlan: 'Are you sure you want to delete this menu?',
    weight: 'Weight',
    mealsPerDay: 'Meals per day',
    meal: 'meal',
    meals: 'meals',
    weightEvolution: 'Weight tracking',
    vetHistory: 'Vet history',
    vetVisits: 'Vet visits',
    newVisit: '+ New visit',
    visitDate: 'Visit date',
    nextAppointment: 'Next appointment (optional)',
    reason: 'Reason',
    reasonPlaceholder: 'Annual checkup, vaccination...',
    description: 'Description',
    descriptionPlaceholder: 'Visit description...',
    treatment: 'Treatment',
    treatmentPlaceholder: 'Medication, instructions, notes...',
    saveRecord: 'Save record',
    noVetRecords: 'No vet records yet.',
    addFirstVisit: '+ Add first visit',
    nextVisit: 'Next appointment',
    treatments: 'Treatments',
    newTreatment: '+ New treatment',
    treatmentName: 'Treatment name',
    treatmentNamePlaceholder: 'Antiparasitic, vaccine...',
    frequency: 'Frequency',
    lastDose: 'Last dose',
    notes: 'Notes (optional)',
    notesPlaceholder: 'Observations...',
    saveTreatment: 'Save treatment',
    noTreatments: 'No treatments registered.',
    adminToday: '✓ Given today',
    daysLeft: 'In {n} days',
    tomorrow: 'Tomorrow',
    today: 'Today',
    overdue: '{n} days overdue',
 }
}

export function useLanguage() {
  const [lang, setLang] = useState('es')
  const t = translations[lang]
  const toggleLang = () => setLang(prev => prev === 'es' ? 'en' : 'es')
  return { lang, t, toggleLang }
}